# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e642f869cd4cad05394a1eb58d8a53d757a11bdb741906a68d7d9c3ee1fdc6ea2a1bf26fbdff7ca77a141b76fec51e34233c374d9dd843e52bd5594b250b7d46

test:
  secret_key_base: 64767dd1d01436f516c8969837734734db7d539d45eb9bd3fcb4fa922b9065f917ebfe22aa4a349467a354279bbea33bf71a80e46a06f0761bb8418f7717454e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
